version: '3.1' 

services:
 
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpNetwork 

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST : db
      MYSQL_ROOT_PASSWORD: password  
    networks:
      - wpNetwork

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    volumes: ["./:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: db:3306 
      WORDPRESS_DB_USER: wordpress 
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpNetwork

networks:
  wpNetwork:
volumes:
  db_data: 
